name: fire_alarm
description: "A smart fire alarm and alert system application."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  http: ^1.5.0
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  geolocator: ^14.0.2
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/gas_meter.png
    - assets/icons/
    - assets/sounds/alarm1.mp3
    - assets/sounds/alarm2.mp3
    - assets/sounds/fire_alarm.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
